In [31]:
import os

import pandas as pd
import numpy as np

import functions.cnn_helpers as help_funcs

# DNA MERFISH data (Su et al. 2020)

## Read distance info and save as arrays

In [25]:
dist_data = pd.read_csv('../data/Su_2020/selected_structures_95_1000_nm_thr.tsv', sep='\t')
transc_data = pd.read_csv('../data/Su_2020/transcriptional_data_95_1000_nm_thr.tsv', sep='\t')

dataset = pd.merge(dist_data, transc_data.iloc[:, :2], how='left', on='Chromosome copy number')

n_loci = 38

### Iterate through all structures and save them as an image

In [28]:
for id, row in dataset.iterrows():
    
    struct_id = int(row['Chromosome copy number'])
    state = int(row['BACH1'])
    if state == 0:
        state_save = 'inactive'
    else:
        state_save = 'active'
    
    dists = row.iloc[1 : -1]
    
    locus_i = 0
    dist_i = np.zeros((n_loci, n_loci))
    
    for i in range(0, n_loci):
        for j in range(i + 1, n_loci):
            dist_i[i,j] = dists.iloc[locus_i]
            
            locus_i += 1
    
    dist_i = dist_i + dist_i.T
    
    
    dist_i = pd.DataFrame(dist_i)
    dist_i.to_csv(f"../data/Su_2020/distance_maps_95_1000/{state_save}/structure_{struct_id}.tsv", sep='\t', header = False, index=False)

## Create splits and save them before (.png) and after (.tsv) normalization

In [29]:
help_funcs.kfold_splits(src_folder = '../data/Su_2020/distance_maps_95_1000/', dst_folder = '../data/Su_2020/CNN_splits_balanced_95_1000')

Creating fold 1/5...
Train size: 1556, Validation size: 638, Test size: 638
Creating fold 2/5...
Train size: 1556, Validation size: 638, Test size: 638
Creating fold 3/5...
Train size: 1556, Validation size: 638, Test size: 638
Creating fold 4/5...
Train size: 1556, Validation size: 638, Test size: 638
Creating fold 5/5...
Train size: 1556, Validation size: 638, Test size: 638
Created 5 stratified splits under '../data/Su_2020/CNN_splits_balanced_95_1000'.

In [5]:
samples = []

# Subfolders are class labels
classes = sorted(
    [
        class_i
        for class_i in os.listdir('../data/Su_2020/CNN_splits_balanced_zscore/fold_0/test')
        if os.path.isdir(os.path.join('../data/Su_2020/CNN_splits_balanced_zscore/fold_0/test', class_i))
    ],
    reverse=True,
)
class_to_idx = {cls: idx for idx, cls in enumerate(classes)}

for label in os.listdir('../data/Su_2020/CNN_splits_balanced_zscore/fold_0/test'):
    class_dir = os.path.join('../data/Su_2020/CNN_splits_balanced_zscore/fold_0/test', label)
    if not os.path.isdir(class_dir):
        continue

    for fname in os.listdir(class_dir):
        if fname.endswith(".tsv"):
            path = os.path.join(class_dir, fname)
            samples.append((path, int(class_to_idx[label])))

# DNA MERFISH data (Su et al. 2020) - simulated dataset

## Read matrices, fill missing triangles and convert from Amber A.U. to real physical nanometers

In [55]:
transc_data = pd.read_csv('../data/Su_2020/simulated_dataset/structures_transcription_data.tsv', sep='\t')
#transc_data = transc_data[['Transcription', 'structure']]

In [56]:
transc_data

,1-2,1-3,1-4,1-5,1-6,1-7,1-8,1-9,1-10,2-3,...,7-8,7-9,7-10,8-9,8-10,9-10,Chromosome copy number,Transcription,dist_index,structure
0,7.0,7.0,7.0,22.0,37.0,7.0,22.0,7.0,7.0,7.0,...,22.0,22.0,7.0,22.0,7.0,22.0,1091,0,1,0
1,7.0,22.0,127.0,127.0,112.0,232.0,157.0,187.0,217.0,22.0,...,97.0,52.0,67.0,37.0,112.0,82.0,7454,1,2,813
2,7.0,37.0,97.0,52.0,52.0,142.0,157.0,142.0,217.0,37.0,...,22.0,157.0,82.0,172.0,67.0,202.0,7780,0,3,1412
3,7.0,37.0,157.0,97.0,127.0,112.0,67.0,127.0,112.0,37.0,...,97.0,82.0,202.0,67.0,187.0,232.0,1654,0,4,1772
4,7.0,52.0,82.0,67.0,157.0,187.0,157.0,277.0,202.0,37.0,...,67.0,157.0,67.0,157.0,82.0,82.0,10368,1,5,2493
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3010,322.0,337.0,352.0,202.0,217.0,112.0,37.0,52.0,7.0,52.0,...,127.0,82.0,97.0,97.0,52.0,52.0,11786,0,2999,1499436
3011,337.0,127.0,37.0,142.0,67.0,142.0,232.0,187.0,247.0,367.0,...,142.0,97.0,112.0,247.0,187.0,112.0,9630,1,3000,1499987
3012,337.0,142.0,172.0,187.0,202.0,202.0,187.0,322.0,202.0,202.0,...,157.0,187.0,202.0,172.0,67.0,142.0,3224,0,3001,1500090
3013,367.0,262.0,247.0,112.0,247.0,217.0,112.0,127.0,172.0,142.0,...,112.0,82.0,187.0,52.0,82.0,127.0,8853,1,3002,1500772
3014,397.0,337.0,382.0,277.0,247.0,172.0,187.0,157.0,262.0,67.0,...,67.0,112.0,247.0,127.0,232.0,127.0,6953,1,3003,1501071

In [57]:
transc_data.head()

,1-2,1-3,1-4,1-5,1-6,1-7,1-8,1-9,1-10,2-3,...,7-8,7-9,7-10,8-9,8-10,9-10,Chromosome copy number,Transcription,dist_index,structure
0,7.0,7.0,7.0,22.0,37.0,7.0,22.0,7.0,7.0,7.0,...,22.0,22.0,7.0,22.0,7.0,22.0,1091,0,1,0
1,7.0,22.0,127.0,127.0,112.0,232.0,157.0,187.0,217.0,22.0,...,97.0,52.0,67.0,37.0,112.0,82.0,7454,1,2,813
2,7.0,37.0,97.0,52.0,52.0,142.0,157.0,142.0,217.0,37.0,...,22.0,157.0,82.0,172.0,67.0,202.0,7780,0,3,1412
3,7.0,37.0,157.0,97.0,127.0,112.0,67.0,127.0,112.0,37.0,...,97.0,82.0,202.0,67.0,187.0,232.0,1654,0,4,1772
4,7.0,52.0,82.0,67.0,157.0,187.0,157.0,277.0,202.0,37.0,...,67.0,157.0,67.0,157.0,82.0,82.0,10368,1,5,2493

In [59]:
original_mats_folder = '../data/Su_2020/simulated_dataset/matrices_AU_upper_diagonal'

dist_mats = os.listdir(original_mats_folder)

In [62]:
# Go through each matrix, process and save according to transcriptional state
scaling_factor = 0.0237699544

for mat_i_file in dist_mats:
    mat_i = pd.read_csv(f'{original_mats_folder}/{mat_i_file}', sep='\t', header=None).to_numpy() / scaling_factor / 10
    
    mat_i[np.isnan(mat_i)] = 0
    mat_i = mat_i + np.transpose(mat_i)

    frame = int(mat_i_file.split('_')[-1].split('.')[0])
    frame_transc = transc_data[transc_data['structure'] == frame]['Transcription'].values[0]
     
    if frame_transc == 0:
        state_save = 'inactive'
    else:
        state_save = 'active'
    
    mat_i = pd.DataFrame(mat_i)
    mat_i.to_csv(f"../data/Su_2020/simulated_dataset/matrices_transformed_classified/{state_save}/structure_{frame}.tsv", sep='\t', header = False, index=False)

## Create splits and save them before (.png) and after (.tsv) normalization

In [63]:
help_funcs.kfold_splits(src_folder = '../data/Su_2020/simulated_dataset/matrices_transformed_classified/', dst_folder = '../data/Su_2020/simulated_dataset/CNN_splits_balanced_95_1000')

Creating fold 1/5...
Train size: 1466, Validation size: 603, Test size: 603
Creating fold 2/5...
Train size: 1466, Validation size: 603, Test size: 603
Creating fold 3/5...
Train size: 1466, Validation size: 603, Test size: 603
Creating fold 4/5...
Train size: 1466, Validation size: 603, Test size: 603
Creating fold 5/5...
Train size: 1466, Validation size: 603, Test size: 603
Created 5 stratified splits under '../data/Su_2020/simulated_dataset/CNN_splits_balanced_95_1000'.

In [66]:
len(os.listdir('../data/Su_2020/simulated_dataset/CNN_splits_balanced_95_1000_zscore/fold_4/test/inactive'))

359

In [119]:
samples = []

# Subfolders are class labels
classes = sorted(
    [
        class_i
        for class_i in os.listdir('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test')
        if os.path.isdir(os.path.join('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test', class_i))
    ],
    reverse=True,
)
class_to_idx = {cls: idx for idx, cls in enumerate(classes)}

for label in os.listdir('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test'):
    class_dir = os.path.join('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test', label)
    if not os.path.isdir(class_dir):
        continue

    for fname in os.listdir(class_dir):
        if fname.endswith(".tsv"):
            path = os.path.join(class_dir, fname)
            samples.append((path, int(class_to_idx[label])))

In [120]:
samples

[('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1248573.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_666262.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_846540.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_23567.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_314629.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_995297.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_772001.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_625011.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1134548.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_900139.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_277007.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_117992.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1477095.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_728865.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1192007.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1010010.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_881963.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_3207.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_871489.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1435703.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_140572.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1150620.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1772.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1174621.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_267015.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1149563.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1057991.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_628046.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1133768.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_628708.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_204000.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_971503.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_862219.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1097578.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_830013.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1302054.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1078026.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_852721.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1081534.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1290495.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_675787.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_770614.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1194449.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_275028.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_79131.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_770348.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_684578.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1399853.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1092000.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_230000.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_645085.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_986414.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_538001.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_658017.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1175089.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1006714.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1459971.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_14910.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_93880.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_683028.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_699500.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_290710.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1319061.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1420718.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1260601.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1061000.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_523185.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1206779.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_315877.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_101676.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_233654.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_49816.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_802500.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_779597.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_482776.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_530852.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_975213.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1389673.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_766064.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_980305.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1041500.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_5117.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_576967.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1420385.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1315603.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_558425.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1282557.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_222111.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1258501.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_664614.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_191997.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_572384.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_86999.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_859588.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_630872.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1155301.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_474521.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_665286.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_348652.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1443623.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1453430.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_205236.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1151952.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_361995.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1131256.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1028908.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_216843.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1267453.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_741078.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_679257.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1308042.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_257822.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_294100.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1487500.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_498575.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_745627.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_130949.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_156414.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_715004.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_427783.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1000511.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1410250.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_416572.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1067983.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_952746.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1330122.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_71683.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_88540.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_688094.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_430370.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_823550.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_604509.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_567771.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1231375.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_382001.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_981537.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_115528.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_28898.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1021294.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1110049.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1132571.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1264969.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_341470.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_38121.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_324001.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_843112.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_371000.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1073659.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_549840.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1251483.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_210005.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_769094.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1360448.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_245039.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1043002.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_814842.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_551607.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1470561.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_279663.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_90047.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_449521.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_297006.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_75039.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1375129.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_66079.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_262514.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_172218.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_524530.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1426500.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_990795.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1068089.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_871595.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_1471317.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_232108.tsv',
  0),
 ('../data/Su_2020/simulated_dataset/CNN_splits_balanced_zscore/fold_0/test/inactive/structure_128103.tsv',
  0),

# ORCA data (Mateo et al. 2020)

## Read distance info and save as arrays

In [42]:
dist_data = pd.read_csv('../data/Mateo_2019/selected_structures_75_5000_filtered.tsv', sep='\t')
transc_data = pd.read_csv('../data/Mateo_2019/transcriptional_data_75_5000_filtered.tsv', sep='\t')

dataset = pd.merge(dist_data, transc_data.iloc[:, :2], how='left', on='cellNumber')

n_loci = 52

# Shuffle labels to test performance
labels = np.array(dataset['Abd-A_Intron'])
labels = np.random.permutation(labels)
dataset['Abd-A_Intron'] = labels

In [44]:
dataset['Abd-A_Intron'].value_counts()

Abd-A_Intron
0    1641
1     653
Name: count, dtype: int64

### Iterate through all structures and save them as an image

In [46]:
for id, row in dataset.iterrows():
    
    struct_id = int(row['cellNumber'])
    state = int(row['Abd-A_Intron'])
    if state == 0:
        state_save = 'inactive'
    else:
        state_save = 'active'
    
    dists = row.iloc[1 : -1]
    
    locus_i = 0
    dist_i = np.zeros((n_loci, n_loci))
    
    for i in range(0, n_loci):
        for j in range(i + 1, n_loci):
            dist_i[i,j] = dists.iloc[locus_i]
            
            locus_i += 1
    
    dist_i = dist_i + dist_i.T
    
    
    dist_i = pd.DataFrame(dist_i)
    dist_i.to_csv(f"../data/Mateo_2019/distance_maps_75_5000_filtered_full_shuffled/{state_save}/structure_{struct_id}.tsv", sep='\t', header = False, index=False)

## Create splits and save them before (.png) and after (.tsv) normalization

In [47]:
help_funcs.final_split(src_folder = '../data/Mateo_2019/distance_maps_75_5000_filtered_full_shuffled/', dst_folder = '../data/Mateo_2019/CNN_splits_balanced_75_5000_filtered_full_shuffled', test_size=0.2)

Train size: 1044, Test size: 459
Created splits under '../data/Mateo_2019/CNN_splits_balanced_75_5000_filtered_full_shuffled'.

In [ ]:
# Also try with unbalanced dataset
#help_funcs.kfold_splits_unbalanced(src_folder = '../data/Mateo_2019/distance_maps_75_5000_filtered/', dst_folder = '../data/Mateo_2019/CNN_splits_unbalanced_75_5000_filtered', test_size=0.2, val_size=0.25)

Creating fold 1/5...
Train size: 1376, Validation size: 459, Test size: 459
Creating fold 2/5...
Train size: 1376, Validation size: 459, Test size: 459
Creating fold 3/5...
Train size: 1376, Validation size: 459, Test size: 459
Creating fold 4/5...
Train size: 1376, Validation size: 459, Test size: 459
Creating fold 5/5...
Train size: 1376, Validation size: 459, Test size: 459
Created 5 stratified splits under '../data/Mateo_2019/CNN_splits_unbalanced_75_5000_filtered'.

In [22]:
samples = []

# Subfolders are class labels
classes = sorted(
    [
        class_i
        for class_i in os.listdir('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test')
        if os.path.isdir(os.path.join('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test', class_i))
    ],
    reverse=True,
)
class_to_idx = {cls: idx for idx, cls in enumerate(classes)}

for label in os.listdir('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test'):
    class_dir = os.path.join('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test', label)
    if not os.path.isdir(class_dir):
        continue

    for fname in os.listdir(class_dir):
        if fname.endswith(".tsv"):
            path = os.path.join(class_dir, fname)
            samples.append((path, int(class_to_idx[label])))

In [23]:
samples

[('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_24585.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_12751.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_45609.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_10146.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_27926.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_33953.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_49741.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_17615.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_18526.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_2898.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_43250.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_40759.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_11516.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_17167.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_44259.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_49796.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_51867.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_35339.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_17826.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_29076.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_32330.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_31611.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_5852.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_33006.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_29738.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_40956.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_31163.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_21370.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_40942.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_24208.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_23567.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_53080.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_22679.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_43293.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_25670.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_10813.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_4769.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_35852.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_5477.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_49557.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_46664.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_21827.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_40215.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_50006.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_19360.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_49543.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_37089.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_48885.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_16047.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_50012.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_35846.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_45379.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_10350.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_53255.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_44729.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_8609.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_11066.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_45351.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_7248.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_47234.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_51456.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_43052.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_3748.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_49594.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_14687.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_35649.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_10393.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_18081.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_6181.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_47591.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_21614.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_34219.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_46076.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_8999.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_26782.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_775.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_3172.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_46710.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_16133.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_11884.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_35932.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_54300.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_19566.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_4147.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_6750.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_48067.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_19228.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_11660.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_26972.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_17577.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_29499.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_37894.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_12396.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_30651.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_30137.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_34351.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_21012.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_43697.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_35701.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_28036.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_27311.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_43683.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_22269.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_2287.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_26769.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_20697.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_8225.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_53679.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_42012.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_4379.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_50416.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_7664.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_50402.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_9891.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_26594.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_33827.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_5715.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_1573.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_6234.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_41241.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_48265.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_2720.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_22916.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_43324.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_39488.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_47142.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_47624.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_32250.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_8580.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_39463.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_29670.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_17946.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_34147.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_24354.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_29664.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_31995.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_24426.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_12194.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_31765.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_43495.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_22719.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_38755.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_21204.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_25062.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_25704.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_21562.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_39338.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_49807.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_47194.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_40823.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_22718.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_25077.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_21239.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_49191.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_24341.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_29103.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_33629.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_2912.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_6547.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_28584.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_3359.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_34813.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_48516.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_20866.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_15611.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_4422.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_43331.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_2735.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_14269.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_45740.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_18453.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_29856.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_17760.tsv',
  0),
 ('../data/Mateo_2019/CNN_splits_balanced_50_5000_filtered_zscore/fold_0/test/inactive/structure_36976.tsv',
  0),

# ORCA MERFISH data (Mateo et al. 2019) - simulated dataset

## Read matrices, fill missing triangles and convert from Amber A.U. to real physical nanometers

In [25]:
transc_data = pd.read_csv('../data/Mateo_2019/simulated_dataset/structures_transcription_data.tsv', sep='\t')
#transc_data = transc_data[['Transcription', 'structure']]

In [26]:
transc_data.head()

,1-2,1-3,1-4,1-5,1-6,1-7,1-8,1-9,1-10,2-3,...,7-8,7-9,7-10,8-9,8-10,9-10,cellNumber,Transcription,dist_index,structure
0,2,2,2,6,10,2,6,10,2,6,...,6,10,6,6,6,10,31299.0,1,1,0
1,2,2,6,14,14,18,22,10,6,2,...,6,10,14,14,22,6,19306.0,0,2,528
2,2,6,6,10,10,6,10,6,10,6,...,14,6,14,10,10,14,2780.0,0,3,1001
3,2,6,6,10,14,10,10,14,14,6,...,10,10,10,10,10,2,32380.0,0,4,1500
4,2,6,6,26,18,30,50,34,30,10,...,30,10,14,22,22,10,32290.0,1,5,2147

In [27]:
original_mats_folder = '../data/Mateo_2019/simulated_dataset/matrices_AU_upper_diagonal'

dist_mats = os.listdir(original_mats_folder)

In [28]:
dist_mats

['frame_1912_910254.tsv',
 'frame_1403_668181.tsv',
 'frame_140_66568.tsv',
 'frame_1962_932006.tsv',
 'frame_1717_817545.tsv',
 'frame_1393_663000.tsv',
 'frame_1242_592056.tsv',
 'frame_1521_726123.tsv',
 'frame_463_220077.tsv',
 'frame_1979_940031.tsv',
 'frame_982_469600.tsv',
 'frame_2082_986471.tsv',
 'frame_1882_896141.tsv',
 'frame_1599_764056.tsv',
 'frame_1873_891838.tsv',
 'frame_651_311511.tsv',
 'frame_1167_556548.tsv',
 'frame_1418_675940.tsv',
 'frame_509_242022.tsv',
 'frame_1034_493817.tsv',
 'frame_1518_724659.tsv',
 'frame_1786_850503.tsv',
 'frame_276_130893.tsv',
 'frame_1159_552618.tsv',
 'frame_1891_900584.tsv',
 'frame_1949_926270.tsv',
 'frame_1399_666120.tsv',
 'frame_278_131000.tsv',
 'frame_1388_660553.tsv',
 'frame_774_372042.tsv',
 'frame_1710_814163.tsv',
 'frame_548_261824.tsv',
 'frame_978_468484.tsv',
 'frame_566_270508.tsv',
 'frame_824_396587.tsv',
 'frame_1711_814523.tsv',
 'frame_1236_589017.tsv',
 'frame_953_455880.tsv',
 'frame_1549_739503.tsv',
 'frame_1280_609490.tsv',
 'frame_1211_577012.tsv',
 'frame_1360_648598.tsv',
 'frame_2181_1030020.tsv',
 'frame_2078_984471.tsv',
 'frame_174_82505.tsv',
 'frame_1354_645515.tsv',
 'frame_310_146002.tsv',
 'frame_216_103022.tsv',
 'frame_1343_640510.tsv',
 'frame_789_379808.tsv',
 'frame_1204_574000.tsv',
 'frame_1460_696555.tsv',
 'frame_153_72579.tsv',
 'frame_234_110579.tsv',
 'frame_1986_943504.tsv',
 'frame_91_44363.tsv',
 'frame_294_138252.tsv',
 'frame_757_364009.tsv',
 'frame_983_470103.tsv',
 'frame_1305_621987.tsv',
 'frame_485_230738.tsv',
 'frame_2178_1028610.tsv',
 'frame_196_93491.tsv',
 'frame_299_140507.tsv',
 'frame_1844_877946.tsv',
 'frame_1524_727006.tsv',
 'frame_1618_773682.tsv',
 'frame_1223_583035.tsv',
 'frame_1378_655628.tsv',
 'frame_841_404018.tsv',
 'frame_1736_827018.tsv',
 'frame_44_21290.tsv',
 'frame_168_79547.tsv',
 'frame_1718_818038.tsv',
 'frame_1859_885014.tsv',
 'frame_378_179863.tsv',
 'frame_623_298158.tsv',
 'frame_324_152736.tsv',
 'frame_1281_609576.tsv',
 'frame_1679_800508.tsv',
 'frame_1023_488026.tsv',
 'frame_1674_798001.tsv',
 'frame_214_102001.tsv',
 'frame_1848_879508.tsv',
 'frame_1876_893024.tsv',
 'frame_413_196576.tsv',
 'frame_2183_1031242.tsv',
 'frame_2138_1011503.tsv',
 'frame_1839_875540.tsv',
 'frame_1091_520115.tsv',
 'frame_2073_981514.tsv',
 'frame_1362_649752.tsv',
 'frame_1613_771249.tsv',
 'frame_2165_1023688.tsv',
 'frame_2096_991651.tsv',
 'frame_1723_820537.tsv',
 'frame_1285_611807.tsv',
 'frame_1189_567027.tsv',
 'frame_415_197501.tsv',
 'frame_1639_782810.tsv',
 'frame_795_382476.tsv',
 'frame_1854_882546.tsv',
 'frame_1805_860025.tsv',
 'frame_1006_480516.tsv',
 'frame_1928_916592.tsv',
 'frame_805_387015.tsv',
 'frame_823_396132.tsv',
 'frame_1334_636003.tsv',
 'frame_387_183501.tsv',
 'frame_2037_965525.tsv',
 'frame_1945_924025.tsv',
 'frame_385_182906.tsv',
 'frame_376_178594.tsv',
 'frame_375_178001.tsv',
 'frame_1701_810272.tsv',
 'frame_1571_750304.tsv',
 'frame_96_46698.tsv',
 'frame_1600_764803.tsv',
 'frame_2005_952993.tsv',
 'frame_390_185031.tsv',
 'frame_1830_871980.tsv',
 'frame_702_337054.tsv',
 'frame_649_310504.tsv',
 'frame_492_233563.tsv',
 'frame_1119_533501.tsv',
 'frame_106_51022.tsv',
 'frame_590_282468.tsv',
 'frame_1532_731238.tsv',
 'frame_203_96878.tsv',
 'frame_1164_555072.tsv',
 'frame_2057_974502.tsv',
 'frame_748_359621.tsv',
 'frame_1316_627401.tsv',
 'frame_1594_761500.tsv',
 'frame_1826_869628.tsv',
 'frame_101_48503.tsv',
 'frame_1675_798535.tsv',
 'frame_1079_514681.tsv',
 'frame_723_347703.tsv',
 'frame_1150_548561.tsv',
 'frame_659_315943.tsv',
 'frame_609_291501.tsv',
 'frame_236_111821.tsv',
 'frame_724_348125.tsv',
 'frame_561_268243.tsv',
 'frame_1625_776574.tsv',
 'frame_1593_761001.tsv',
 'frame_1368_652499.tsv',
 'frame_308_145004.tsv',
 'frame_305_143516.tsv',
 'frame_1556_743274.tsv',
 'frame_1394_663514.tsv',
 'frame_1149_548003.tsv',
 'frame_332_156866.tsv',
 'frame_137_65539.tsv',
 'frame_105_50646.tsv',
 'frame_1268_604545.tsv',
 'frame_1647_786308.tsv',
 'frame_1680_801019.tsv',
 'frame_803_386074.tsv',
 'frame_1525_727531.tsv',
 'frame_1116_532442.tsv',
 'frame_1577_753016.tsv',
 'frame_1146_546503.tsv',
 'frame_164_77534.tsv',
 'frame_314_148131.tsv',
 'frame_1185_565503.tsv',
 'frame_1208_576055.tsv',
 'frame_2041_967280.tsv',
 'frame_1983_942152.tsv',
 'frame_2004_952484.tsv',
 'frame_985_471003.tsv',
 'frame_1373_654111.tsv',
 'frame_1918_912587.tsv',
 'frame_263_124859.tsv',
 'frame_1100_524127.tsv',
 'frame_728_350117.tsv',
 'frame_1698_808519.tsv',
 'frame_2036_965013.tsv',
 'frame_703_337953.tsv',
 'frame_2109_998000.tsv',
 'frame_1663_792679.tsv',
 'frame_992_474614.tsv',
 'frame_1601_765018.tsv',
 'frame_1754_835437.tsv',
 'frame_1822_867524.tsv',
 'frame_1545_737973.tsv',
 'frame_1172_559001.tsv',
 'frame_645_308534.tsv',
 'frame_161_76625.tsv',
 'frame_2060_976061.tsv',
 'frame_515_245001.tsv',
 'frame_1869_889887.tsv',
 'frame_1846_878989.tsv',
 'frame_1277_608166.tsv',
 'frame_820_394675.tsv',
 'frame_1470_701526.tsv',
 'frame_1217_580055.tsv',
 'frame_62_30107.tsv',
 'frame_458_217516.tsv',
 'frame_765_367670.tsv',
 'frame_750_360948.tsv',
 'frame_134_64571.tsv',
 'frame_576_275582.tsv',
 'frame_1165_555578.tsv',
 'frame_425_202074.tsv',
 'frame_766_368029.tsv',
 'frame_835_401674.tsv',
 'frame_838_403101.tsv',
 'frame_1201_572728.tsv',
 'frame_1059_505023.tsv',
 'frame_389_184506.tsv',
 'frame_433_206074.tsv',
 'frame_1509_720775.tsv',
 'frame_589_281576.tsv',
 'frame_1550_740011.tsv',
 'frame_854_410004.tsv',
 'frame_1487_710000.tsv',
 'frame_436_207025.tsv',
 'frame_837_402524.tsv',
 'frame_467_221504.tsv',
 'frame_1095_522218.tsv',
 'frame_240_113995.tsv',
 'frame_22_10532.tsv',
 'frame_1104_526002.tsv',
 'frame_1726_822078.tsv',
 'frame_1163_554532.tsv',
 'frame_1802_858870.tsv',
 'frame_1261_601867.tsv',
 'frame_2156_1019544.tsv',
 'frame_286_135022.tsv',
 'frame_1302_620424.tsv',
 'frame_1145_546134.tsv',
 'frame_2099_993030.tsv',
 'frame_256_121759.tsv',
 'frame_245_116022.tsv',
 'frame_769_369627.tsv',
 'frame_1982_941813.tsv',
 'frame_2042_967648.tsv',
 'frame_1286_612132.tsv',
 'frame_1439_686267.tsv',
 'frame_695_333534.tsv',
 'frame_690_331087.tsv',
 'frame_1671_796823.tsv',
 'frame_2120_1003581.tsv',
 'frame_2023_960061.tsv',
 'frame_1894_901514.tsv',
 'frame_2171_1025527.tsv',
 'frame_1092_520520.tsv',
 'frame_1516_723529.tsv',
 'frame_171_81029.tsv',
 'frame_2187_1033039.tsv',
 'frame_298_140031.tsv',
 'frame_593_283586.tsv',
 'frame_1901_905029.tsv',
 'frame_2074_982119.tsv',
 'frame_834_401341.tsv',
 'frame_1634_780578.tsv',
 'frame_2130_1008570.tsv',
 'frame_1369_652782.tsv',
 'frame_1807_861004.tsv',
 'frame_519_247095.tsv',
 'frame_1407_670000.tsv',
 'frame_1965_933609.tsv',
 'frame_1384_658847.tsv',
 'frame_1934_919512.tsv',
 'frame_1012_482513.tsv',
 'frame_435_206906.tsv',
 'frame_2152_1018033.tsv',
 'frame_223_106466.tsv',
 'frame_560_267509.tsv',
 'frame_1991_945608.tsv',
 'frame_726_349499.tsv',
 'frame_158_75016.tsv',
 'frame_342_161769.tsv',
 'frame_605_289642.tsv',
 'frame_535_255020.tsv',
 'frame_1729_823934.tsv',
 'frame_1514_722527.tsv',
 'frame_189_89742.tsv',
 'frame_2137_1011015.tsv',
 'frame_377_179018.tsv',
 'frame_781_375607.tsv',
 'frame_2031_963038.tsv',
 'frame_1909_908527.tsv',
 'frame_827_397530.tsv',
 'frame_1330_634120.tsv',
 'frame_1126_537028.tsv',
 'frame_328_154501.tsv',
 'frame_1683_802527.tsv',
 'frame_1111_529564.tsv',
 'frame_577_276035.tsv',
 'frame_35_17279.tsv',
 'frame_1363_650042.tsv',
 'frame_1262_602009.tsv',
 'frame_1952_927481.tsv',
 'frame_668_320499.tsv',
 'frame_1764_840394.tsv',
 'frame_584_279037.tsv',
 'frame_1508_720047.tsv',
 'frame_616_294505.tsv',
 'frame_1924_915346.tsv',
 'frame_1633_780484.tsv',
 'frame_1193_569007.tsv',
 'frame_449_213549.tsv',
 'frame_718_345034.tsv',
 'frame_797_383043.tsv',
 'frame_784_377015.tsv',
 'frame_60_29000.tsv',
 'frame_102_49000.tsv',
 'frame_464_220638.tsv',
 'frame_227_108032.tsv',
 'frame_1263_602501.tsv',
 'frame_122_59339.tsv',
 'frame_2173_1026962.tsv',
 'frame_514_244982.tsv',
 'frame_2129_1008000.tsv',
 'frame_1596_762520.tsv',
 'frame_138_65540.tsv',
 'frame_159_75511.tsv',
 'frame_1637_781532.tsv',
 'frame_100_48017.tsv',
 'frame_1706_812203.tsv',
 'frame_2015_956544.tsv',
 'frame_487_231536.tsv',
 'frame_618_295616.tsv',
 'frame_1975_938281.tsv',
 'frame_1222_582745.tsv',
 'frame_2140_1012855.tsv',
 'frame_972_465049.tsv',
 'frame_1072_511127.tsv',
 'frame_964_461048.tsv',
 'frame_957_457578.tsv',
 'frame_491_233185.tsv',
 'frame_1218_580743.tsv',
 'frame_400_190001.tsv',
 'frame_683_327521.tsv',
 'frame_1546_738486.tsv',
 'frame_2170_1025202.tsv',
 'frame_603_288556.tsv',
 'frame_1429_681359.tsv',
 'frame_1076_513016.tsv',
 'frame_333_157047.tsv',
 'frame_1699_809041.tsv',
 'frame_483_229661.tsv',
 'frame_58_28043.tsv',
 'frame_611_292502.tsv',
 'frame_8_4010.tsv',
 'frame_1239_590508.tsv',
 'frame_1737_827661.tsv',
 'frame_2018_958190.tsv',
 'frame_495_235013.tsv',
 'frame_1010_482000.tsv',
 'frame_960_459030.tsv',
 'frame_2027_962008.tsv',
 'frame_1782_848524.tsv',
 'frame_1692_806144.tsv',
 'frame_826_397005.tsv',
 'frame_1652_788000.tsv',
 'frame_207_98793.tsv',
 'frame_82_40238.tsv',
 'frame_1575_752385.tsv',
 'frame_644_308004.tsv',
 'frame_933_446319.tsv',
 'frame_2026_961960.tsv',
 'frame_1783_849483.tsv',
 'frame_68_33096.tsv',
 'frame_1801_858270.tsv',
 'frame_1563_746020.tsv',
 'frame_1207_575539.tsv',
 'frame_104_50027.tsv',
 'frame_800_384655.tsv',
 'frame_1645_785511.tsv',
 'frame_520_247664.tsv',
 'frame_1004_479935.tsv',
 'frame_1377_655504.tsv',
 'frame_349_165076.tsv',
 'frame_926_443544.tsv',
 'frame_372_176501.tsv',
 'frame_1860_885779.tsv',
 'frame_1405_669456.tsv',
 'frame_1425_679076.tsv',
 'frame_1016_484650.tsv',
 'frame_327_154011.tsv',
 'frame_302_142482.tsv',
 'frame_330_155500.tsv',
 'frame_393_186518.tsv',
 'frame_237_112005.tsv',
 'frame_2087_988933.tsv',
 'frame_878_421047.tsv',
 'frame_597_285602.tsv',
 'frame_971_464990.tsv',
 'frame_2151_1017602.tsv',
 'frame_1933_919004.tsv',
 'frame_1700_809601.tsv',
 'frame_753_362238.tsv',
 'frame_1444_688903.tsv',
 'frame_112_54000.tsv',
 'frame_70_34000.tsv',
 'frame_1395_664173.tsv',
 'frame_1990_945505.tsv',
 'frame_1720_819223.tsv',
 'frame_942_450479.tsv',
 'frame_1077_513534.tsv',
 'frame_348_164500.tsv',
 'frame_884_423516.tsv',
 'frame_936_447835.tsv',
 'frame_1956_929161.tsv',
 'frame_1712_815024.tsv',
 'frame_892_427503.tsv',
 'frame_1829_871002.tsv',
 'frame_1616_772999.tsv',
 'frame_45_21977.tsv',
 'frame_1225_584032.tsv',
 'frame_925_443206.tsv',
 'frame_1486_709923.tsv',
 'frame_1437_685016.tsv',
 'frame_469_222563.tsv',
 'frame_741_356150.tsv',
 'frame_783_376743.tsv',
 'frame_1527_728510.tsv',
 'frame_1220_581749.tsv',
 'frame_1981_941205.tsv',
 'frame_61_29504.tsv',
 'frame_1709_813590.tsv',
 'frame_909_435255.tsv',
 'frame_1370_653474.tsv',
 'frame_113_54673.tsv',
 'frame_1005_480044.tsv',
 'frame_146_69077.tsv',
 'frame_780_375052.tsv',
 'frame_79_38694.tsv',
 'frame_1814_863516.tsv',
 'frame_542_258587.tsv',
 'frame_341_161002.tsv',
 'frame_465_221005.tsv',
 'frame_187_88508.tsv',
 'frame_211_100944.tsv',
 'frame_1566_747885.tsv',
 'frame_1266_603547.tsv',
 'frame_1253_597505.tsv',
 'frame_1401_667000.tsv',
 'frame_283_133733.tsv',
 'frame_1902_905632.tsv',
 'frame_558_266503.tsv',
 'frame_1003_479429.tsv',
 'frame_771_370523.tsv',
 'frame_2093_990638.tsv',
 'frame_1130_539117.tsv',
 'frame_790_379809.tsv',
 'frame_778_374317.tsv',
 'frame_1867_889052.tsv',
 'frame_937_448015.tsv',
 'frame_715_343727.tsv',
 'frame_638_305435.tsv',
 'frame_1688_804559.tsv',
 'frame_1635_781355.tsv',
 'frame_334_157591.tsv',
 'frame_1864_887515.tsv',
 'frame_175_83047.tsv',
 'frame_1589_759425.tsv',
 'frame_392_186012.tsv',
 'frame_704_338432.tsv',
 'frame_720_346007.tsv',
 'frame_1278_608667.tsv',
 'frame_1249_595873.tsv',
 'frame_595_284583.tsv',
 'frame_1950_926271.tsv',
 'frame_11_5646.tsv',
 'frame_1833_873024.tsv',
 'frame_538_256500.tsv',
 'frame_1379_656017.tsv',
 'frame_280_132422.tsv',
 'frame_812_390997.tsv',
 'frame_2116_1001846.tsv',
 'frame_2162_1022979.tsv',
 'frame_1621_775173.tsv',
 'frame_1617_773142.tsv',
 'frame_2058_975095.tsv',
 'frame_408_194048.tsv',
 'frame_284_134006.tsv',
 'frame_1896_902521.tsv',
 'frame_1140_543661.tsv',
 'frame_836_402176.tsv',
 'frame_592_283063.tsv',
 'frame_696_334045.tsv',
 'frame_66_32009.tsv',
 'frame_1274_607512.tsv',
 'frame_1248_595017.tsv',
 'frame_1798_856713.tsv',
 'frame_40_19000.tsv',
 'frame_570_272626.tsv',
 'frame_1557_743551.tsv',
 'frame_253_120068.tsv',
 'frame_1032_492521.tsv',
 'frame_1258_600186.tsv',
 'frame_1061_506001.tsv',
 'frame_500_237570.tsv',
 'frame_2001_950642.tsv',
 'frame_818_393550.tsv',
 'frame_587_280887.tsv',
 'frame_946_452010.tsv',
 'frame_1766_841149.tsv',
 'frame_1576_752954.tsv',
 'frame_1415_674244.tsv',
 'frame_534_254542.tsv',
 'frame_1564_746534.tsv',
 'frame_1252_597018.tsv',
 'frame_1346_642138.tsv',
 'frame_526_250516.tsv',
 'frame_1791_853198.tsv',
 'frame_462_219701.tsv',
 'frame_1592_760572.tsv',
 'frame_607_290788.tsv',
 'frame_633_303313.tsv',
 'frame_1947_925002.tsv',
 'frame_1322_630348.tsv',
 'frame_2121_1004494.tsv',
 'frame_740_355597.tsv',
 'frame_1702_810523.tsv',
 'frame_761_365828.tsv',
 'frame_772_371020.tsv',
 'frame_166_78535.tsv',
 'frame_945_451503.tsv',
 'frame_963_460904.tsv',
 'frame_322_151543.tsv',
 'frame_1327_632638.tsv',
 'frame_1488_710852.tsv',
 'frame_1987_944015.tsv',
 'frame_1310_624029.tsv',
 'frame_2184_1031600.tsv',
 'frame_445_211546.tsv',
 'frame_641_306896.tsv',
 'frame_1789_852128.tsv',
 'frame_381_181009.tsv',
 'frame_825_396588.tsv',
 'frame_2107_997404.tsv',
 'frame_973_465518.tsv',
 'frame_306_144001.tsv',
 'frame_751_361131.tsv',
 'frame_1177_561538.tsv',
 'frame_1108_528141.tsv',
 'frame_994_475993.tsv',
 'frame_1936_920009.tsv',
 'frame_816_392546.tsv',
 'frame_315_148505.tsv',
 'frame_1042_497591.tsv',
 'frame_1665_793518.tsv',
 'frame_421_200508.tsv',
 'frame_249_118388.tsv',
 'frame_518_246543.tsv',
 'frame_894_428517.tsv',
 'frame_51_24504.tsv',
 'frame_1240_591172.tsv',
 'frame_498_236541.tsv',
 'frame_1454_693508.tsv',
 'frame_2149_1016506.tsv',
 'frame_1762_839017.tsv',
 'frame_889_426190.tsv',
 'frame_1881_895545.tsv',
 'frame_2063_977107.tsv',
 'frame_2067_978507.tsv',
 'frame_1523_727002.tsv',
 'frame_1115_531535.tsv',
 'frame_473_224546.tsv',
 'frame_1232_587030.tsv',
 'frame_815_392164.tsv',
 'frame_1122_535021.tsv',
 'frame_1382_657717.tsv',
 'frame_1538_734420.tsv',
 'frame_1626_777002.tsv',
 'frame_2166_1024451.tsv',
 'frame_455_216051.tsv',
 'frame_1946_924854.tsv',
 'frame_1301_619584.tsv',
 'frame_830_399001.tsv',
 'frame_1203_573555.tsv',
 'frame_996_476546.tsv',
 'frame_1505_718970.tsv',
 'frame_221_105154.tsv',
 'frame_1462_697716.tsv',
 'frame_2071_980583.tsv',
 'frame_52_25000.tsv',
 'frame_1414_673520.tsv',
 'frame_2141_1013188.tsv',
 'frame_697_334660.tsv',
 'frame_1906_907201.tsv',
 'frame_19_9658.tsv',
 'frame_1435_684480.tsv',
 'frame_2032_963640.tsv',
 'frame_1345_641511.tsv',
 'frame_508_241525.tsv',
 'frame_2164_1023040.tsv',
 'frame_156_74011.tsv',
 'frame_559_267004.tsv',
 'frame_2002_951497.tsv',
 'frame_979_468501.tsv',
 'frame_41_19617.tsv',
 'frame_1188_566518.tsv',
 'frame_2068_979453.tsv',
 'frame_1033_493027.tsv',
 'frame_139_66476.tsv',
 'frame_1994_947297.tsv',
 'frame_2134_1010081.tsv',
 'frame_1808_861818.tsv',
 'frame_1758_837010.tsv',
 'frame_1753_834511.tsv',
 'frame_1855_883441.tsv',
 'frame_574_274516.tsv',
 'frame_578_276622.tsv',
 'frame_142_67496.tsv',
 'frame_1468_700547.tsv',
 'frame_155_73986.tsv',
 'frame_107_51988.tsv',
 'frame_1598_763509.tsv',
 'frame_1160_553031.tsv',
 'frame_149_70501.tsv',
 'frame_123_59921.tsv',
 'frame_1410_671607.tsv',
 'frame_1716_817211.tsv',
 'frame_613_293009.tsv',
 'frame_255_121253.tsv',
 'frame_7_3511.tsv',
 'frame_1436_684511.tsv',
 'frame_1152_549508.tsv',
 'frame_1722_820074.tsv',
 'frame_1880_895058.tsv',
 'frame_1279_608687.tsv',
 'frame_670_321199.tsv',
 'frame_2040_966597.tsv',
 'frame_1478_705690.tsv',
 'frame_1931_918080.tsv',
 'frame_192_91129.tsv',
 'frame_1109_528528.tsv',
 'frame_337_159106.tsv',
 'frame_1102_525010.tsv',
 'frame_1530_730090.tsv',
 'frame_1893_901513.tsv',
 'frame_1841_876801.tsv',
 'frame_2119_1003065.tsv',
 'frame_1093_521034.tsv',
 'frame_714_343260.tsv',
 'frame_2114_1000504.tsv',
 'frame_1231_586527.tsv',
 'frame_373_177038.tsv',
 'frame_1387_660183.tsv',
 'frame_2059_975510.tsv',
 'frame_1366_651513.tsv',
 'frame_987_472119.tsv',
 'frame_873_418640.tsv',
 'frame_567_271156.tsv',
 'frame_667_319747.tsv',
 'frame_729_350118.tsv',
 'frame_2090_989504.tsv',
 'frame_791_380057.tsv',
 'frame_632_302617.tsv',
 'frame_1028_490984.tsv',
 'frame_275_130157.tsv',
 'frame_1438_685748.tsv',
 'frame_1935_920004.tsv',
 'frame_1930_917518.tsv',
 'frame_496_235697.tsv',
 'frame_1719_818551.tsv',
 'frame_984_470500.tsv',
 'frame_874_419088.tsv',
 'frame_340_160513.tsv',
 'frame_786_378120.tsv',
 'frame_1796_855529.tsv',
 'frame_1124_536044.tsv',
 'frame_1650_787120.tsv',
 'frame_1993_946517.tsv',
 'frame_300_141011.tsv',
 'frame_1365_651053.tsv',
 'frame_201_95599.tsv',
 'frame_2157_1020108.tsv',
 'frame_30_14651.tsv',
 'frame_819_394196.tsv',
 'frame_1883_896978.tsv',
 'frame_2079_984680.tsv',
 'frame_1304_621035.tsv',
 'frame_76_37409.tsv',
 'frame_808_388542.tsv',
 'frame_1494_713047.tsv',
 'frame_204_97034.tsv',
 'frame_717_344517.tsv',
 'frame_1019_486337.tsv',
 'frame_292_137526.tsv',
 'frame_656_314042.tsv',
 'frame_869_416513.tsv',
 'frame_1623_776044.tsv',
 'frame_476_226021.tsv',
 'frame_731_351087.tsv',
 'frame_394_187028.tsv',
 'frame_636_304637.tsv',
 'frame_1728_823080.tsv',
 'frame_1887_898684.tsv',
 'frame_1114_531162.tsv',
 'frame_121_58505.tsv',
 'frame_745_358005.tsv',
 'frame_1216_579574.tsv',
 'frame_573_274017.tsv',
 'frame_938_448944.tsv',
 'frame_2117_1002000.tsv',
 'frame_1481_707461.tsv',
 'frame_673_322503.tsv',
 'frame_1372_653856.tsv',
 'frame_1000_478006.tsv',
 'frame_712_342163.tsv',
 'frame_326_153563.tsv',
 'frame_1977_939004.tsv',
 'frame_2008_954199.tsv',
 'frame_1123_535890.tsv',
 'frame_1353_645260.tsv',
 'frame_1112_530101.tsv',
 'frame_1687_804206.tsv',
 'frame_1562_745523.tsv',
 'frame_2175_1027502.tsv',
 'frame_1385_659039.tsv',
 'frame_1472_702615.tsv',
 'frame_1053_502429.tsv',
 'frame_513_244000.tsv',
 'frame_494_234515.tsv',
 'frame_1875_892624.tsv',
 'frame_681_326997.tsv',
 'frame_2124_1005729.tsv',
 'frame_1888_899049.tsv',
 'frame_730_350519.tsv',
 'frame_2176_1028332.tsv',
 'frame_1967_934639.tsv',
 'frame_806_387696.tsv',
 'frame_782_376039.tsv',
 'frame_1958_930129.tsv',
 'frame_1817_865045.tsv',
 'frame_2154_1018585.tsv',
 'frame_958_458103.tsv',
 'frame_1090_519607.tsv',
 'frame_1784_849509.tsv',
 'frame_1851_881002.tsv',
 'frame_2110_998927.tsv',
 'frame_1678_800100.tsv',
 'frame_50_24001.tsv',
 'frame_1309_623608.tsv',
 'frame_2100_993997.tsv',
 'frame_336_158505.tsv',
 'frame_2095_991373.tsv',
 'frame_331_156003.tsv',
 'frame_1480_706869.tsv',
 'frame_1246_594003.tsv',
 'frame_746_358591.tsv',
 'frame_1318_628005.tsv',
 'frame_1321_629706.tsv',
 'frame_1944_923550.tsv',
 'frame_1877_893606.tsv',
 'frame_1937_920517.tsv',
 'frame_354_167508.tsv',
 'frame_1578_753808.tsv',
 'frame_1775_845458.tsv',
 'frame_665_318764.tsv',
 'frame_1241_591530.tsv',
 'frame_736_353557.tsv',
 'frame_610_292050.tsv',
 'frame_291_137105.tsv',
 'frame_2038_966011.tsv',
 'frame_2127_1007005.tsv',
 'frame_362_171851.tsv',
 'frame_1964_933010.tsv',
 'frame_303_142503.tsv',
 'frame_1892_901391.tsv',
 'frame_200_95470.tsv',
 'frame_132_63509.tsv',
 'frame_1823_868382.tsv',
 'frame_1359_648084.tsv',
 'frame_1214_578609.tsv',
 'frame_1677_799588.tsv',
 'frame_735_353029.tsv',
 'frame_2044_968513.tsv',
 'frame_862_413502.tsv',
 'frame_229_108500.tsv',
 'frame_359_170077.tsv',
 'frame_1537_733516.tsv',
 'frame_512_243501.tsv',
 'frame_1338_638009.tsv',
 'frame_1533_731624.tsv',
 'frame_2179_1029059.tsv',
 'frame_16_8014.tsv',

In [29]:
transc_data

,1-2,1-3,1-4,1-5,1-6,1-7,1-8,1-9,1-10,2-3,...,7-8,7-9,7-10,8-9,8-10,9-10,cellNumber,Transcription,dist_index,structure
0,2,2,2,6,10,2,6,10,2,6,...,6,10,6,6,6,10,31299.0,1,1,0
1,2,2,6,14,14,18,22,10,6,2,...,6,10,14,14,22,6,19306.0,0,2,528
2,2,6,6,10,10,6,10,6,10,6,...,14,6,14,10,10,14,2780.0,0,3,1001
3,2,6,6,10,14,10,10,14,14,6,...,10,10,10,10,10,2,32380.0,0,4,1500
4,2,6,6,26,18,30,50,34,30,10,...,30,10,14,22,22,10,32290.0,1,5,2147
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2185,62,42,26,34,30,38,22,34,38,26,...,14,10,10,14,22,10,49524.0,0,2065,1032147
2186,62,54,50,50,46,58,58,54,62,18,...,6,10,6,6,6,10,17049.0,1,2066,1032623
2187,66,62,62,62,66,58,70,74,82,6,...,18,18,26,10,14,10,44596.0,0,2067,1033050
2188,66,62,62,62,66,58,70,74,82,6,...,18,18,26,10,14,10,44596.0,0,2067,1033039
2189,66,66,66,66,70,58,66,66,66,10,...,6,10,14,6,6,6,2964.0,0,2068,1033500

In [9]:
# Go through each matrix, process and save according to transcriptional state
scaling_factor = 0.0051234457

for mat_i_file in dist_mats:
    mat_i = pd.read_csv(f'{original_mats_folder}/{mat_i_file}', sep='\t', header=None).to_numpy() / scaling_factor / 10
    
    mat_i[np.isnan(mat_i)] = 0
    mat_i = mat_i + np.transpose(mat_i)

    frame = int(mat_i_file.split('_')[-1].split('.')[0])
    frame_transc = transc_data[transc_data['structure'] == frame]['Transcription'].values[0]
     
    if frame_transc == 0:
        state_save = 'inactive'
    else:
        state_save = 'active'
    
    mat_i = pd.DataFrame(mat_i)
    mat_i.to_csv(f"../data/Mateo_2019/simulated_dataset/matrices_transformed_classified/{state_save}/structure_{frame}.tsv", sep='\t', header = False, index=False)

## Create splits and save them before (.png) and after (.tsv) normalization

In [10]:
help_funcs.kfold_splits(src_folder = '../data/Mateo_2019/simulated_dataset/matrices_transformed_classified/', dst_folder = '../data/Mateo_2019/simulated_dataset/CNN_splits_balanced_75_5000')

Creating fold 1/5...
Train size: 754, Validation size: 438, Test size: 438
Creating fold 2/5...
Train size: 754, Validation size: 438, Test size: 438
Creating fold 3/5...
Train size: 754, Validation size: 438, Test size: 438
Creating fold 4/5...
Train size: 754, Validation size: 438, Test size: 438
Creating fold 5/5...
Train size: 754, Validation size: 438, Test size: 438
Created 5 stratified splits under '../data/Mateo_2019/simulated_dataset/CNN_splits_balanced_75_5000'.

#### Final evaluation with test/train set

In [30]:
# Redo, only dividing into test and training sets
help_funcs.final_split(src_folder = '../data/Mateo_2019/simulated_dataset/matrices_transformed_classified/', dst_folder = '../data/Mateo_2019/simulated_dataset/CNN_splits_balanced_75_5000_full')

Train size: 1006, Test size: 438
Created splits under '../data/Mateo_2019/simulated_dataset/CNN_splits_balanced_75_5000_full'.